"""API routes for Fin-Guard backend."""
from __future__ import annotations

from fastapi import APIRouter, HTTPException

from app.agents.guardian import agent
from app.auth import connect_service, disconnect_service, get_connections
from app.models.schemas import (
    AnalysisRequest,
    AnalysisResponse,
    AuditEntry,
    DashboardState,
    ServiceConnection,
    SpendingThreshold,
)
from app.tools.notifications import clear_alerts, get_alerts

router = APIRouter(prefix="/api", tags=["api"])


# ── Dashboard ────────────────────────────────────────────────────────────────

@router.get("/dashboard", response_model=DashboardState)
async def get_dashboard():
    """Get full dashboard state — connections, alerts, audit log."""
    return DashboardState(
        connections=get_connections(),
        recent_alerts=get_alerts()[-10:],
        audit_log=agent.get_audit_log()[-20:],
        agent_status=agent.status,
    )


# ── Connections (Token Vault) ────────────────────────────────────────────────

@router.get("/connections", response_model=list[ServiceConnection])
async def list_connections():
    """List all service connections and their permission levels."""
    return get_connections()


@router.post("/connections/{service_id}/connect", response_model=ServiceConnection)
async def connect(service_id: str):
    """Connect a service via Auth0 Token Vault.

    This triggers the Connected Accounts OAuth flow.
    All connections are READ-ONLY — Fin-Guard never requests write access.
    """
    try:
        return connect_service(service_id)
    except ValueError as e:
        raise HTTPException(status_code=404, detail=str(e))


@router.post("/connections/{service_id}/disconnect")
async def disconnect(service_id: str):
    """Disconnect a service — revoke Token Vault access instantly.

    Other connections remain active. This is per-service granular revocation.
    """
    if disconnect_service(service_id):
        return {"status": "disconnected", "service_id": service_id}
    raise HTTPException(status_code=404, detail="Service not connected")


# ── Agent Analysis ───────────────────────────────────────────────────────────

@router.post("/analyze", response_model=AnalysisResponse)
async def run_analysis(req: AnalysisRequest | None = None):
    """Trigger the Fin-Guard agent to analyze transactions.

    The agent will:
    1. READ transactions from connected financial API
    2. READ budget from Google Sheets
    3. Detect anomalies
    4. SEND alerts via Slack

    Every action is logged in the audit trail.
    """
    result = await agent.analyze()
    return result


@router.post("/analyze/demo-blocked-write", response_model=AuditEntry)
async def demo_blocked_write():
    """Demonstrate that write operations are BLOCKED.

    Call this endpoint to show that Fin-Guard refuses to modify
    financial data even when explicitly asked. The blocked attempt
    appears in the audit trail.
    """
    return agent.demonstrate_blocked_write()


# ── Alerts ───────────────────────────────────────────────────────────────────

@router.get("/alerts")
async def list_alerts():
    """Get all alerts generated by the agent."""
    return get_alerts()


@router.post("/alerts/clear")
async def clear_all_alerts():
    """Clear all alerts (for demo reset)."""
    clear_alerts()
    return {"status": "cleared"}


# ── Audit Trail ──────────────────────────────────────────────────────────────

@router.get("/audit", response_model=list[AuditEntry])
async def get_audit_trail():
    """Get the full audit trail — every API call the agent has made.

    This is a core Fin-Guard feature: complete transparency about
    what data the agent accessed and when.
    """
    return agent.get_audit_log()


@router.post("/audit/clear")
async def clear_audit():
    """Clear audit trail (for demo reset)."""
    agent.clear_audit_log()
    return {"status": "cleared"}


# ── Demo Reset ───────────────────────────────────────────────────────────────

@router.post("/reset")
async def reset_demo():
    """Reset all state for a fresh demo run."""
    agent.clear_audit_log()
    clear_alerts()
    return {"status": "reset", "message": "All alerts and audit entries cleared"}
